# hash:sha256:fbfca5014718cd23593e79f9a2ab11022c79290cfc4feed7fca30741abf6bf1f
FROM registry.codeocean-test.cajalneuro.com/codeocean/jupyterlab:3.4.4-miniconda4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /
